#!/bin/bash

sudo chmod 777 /dev/kvm -R
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/emulator
emulator -avd Copy_of_Pixel_API_24 & sudo react-native start & sudo react-native run-android  
